// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// source: /usr/share/vpp/api/core/dhcp6_pd_client_cp.api.json

/*
Package dhcp6_pd_client_cp is a generated VPP binary API for 'dhcp6_pd_client_cp' module.

It consists of:
	  4 messages
	  2 services
*/
package dhcp6_pd_client_cp

import (
	bytes "bytes"
	context "context"
	api "git.fd.io/govpp.git/api"
	struc "github.com/lunixbochs/struc"
	io "io"
	strconv "strconv"
)

const (
	// ModuleName is the name of this module.
	ModuleName = "dhcp6_pd_client_cp"
	// APIVersion is the API version of this module.
	APIVersion = "1.0.0"
	// VersionCrc is the CRC of this module.
	VersionCrc = 0x89ef31a7
)

// DHCP6PdClientEnableDisable represents VPP binary API message 'dhcp6_pd_client_enable_disable'.
type DHCP6PdClientEnableDisable struct {
	SwIfIndex   uint32
	PrefixGroup []byte `struc:"[64]byte"`
	Enable      uint8
}

func (*DHCP6PdClientEnableDisable) GetMessageName() string {
	return "dhcp6_pd_client_enable_disable"
}
func (*DHCP6PdClientEnableDisable) GetCrcString() string {
	return "d2caf7ee"
}
func (*DHCP6PdClientEnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

// DHCP6PdClientEnableDisableReply represents VPP binary API message 'dhcp6_pd_client_enable_disable_reply'.
type DHCP6PdClientEnableDisableReply struct {
	Retval int32
}

func (*DHCP6PdClientEnableDisableReply) GetMessageName() string {
	return "dhcp6_pd_client_enable_disable_reply"
}
func (*DHCP6PdClientEnableDisableReply) GetCrcString() string {
	return "e8d4e804"
}
func (*DHCP6PdClientEnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

// IP6AddDelAddressUsingPrefix represents VPP binary API message 'ip6_add_del_address_using_prefix'.
type IP6AddDelAddressUsingPrefix struct {
	SwIfIndex    uint32
	PrefixGroup  []byte `struc:"[64]byte"`
	Address      []byte `struc:"[16]byte"`
	PrefixLength uint8
	IsAdd        uint8
}

func (*IP6AddDelAddressUsingPrefix) GetMessageName() string {
	return "ip6_add_del_address_using_prefix"
}
func (*IP6AddDelAddressUsingPrefix) GetCrcString() string {
	return "3216fd48"
}
func (*IP6AddDelAddressUsingPrefix) GetMessageType() api.MessageType {
	return api.RequestMessage
}

// IP6AddDelAddressUsingPrefixReply represents VPP binary API message 'ip6_add_del_address_using_prefix_reply'.
type IP6AddDelAddressUsingPrefixReply struct {
	Retval int32
}

func (*IP6AddDelAddressUsingPrefixReply) GetMessageName() string {
	return "ip6_add_del_address_using_prefix_reply"
}
func (*IP6AddDelAddressUsingPrefixReply) GetCrcString() string {
	return "e8d4e804"
}
func (*IP6AddDelAddressUsingPrefixReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func init() {
	api.RegisterMessage((*DHCP6PdClientEnableDisable)(nil), "dhcp6_pd_client_cp.DHCP6PdClientEnableDisable")
	api.RegisterMessage((*DHCP6PdClientEnableDisableReply)(nil), "dhcp6_pd_client_cp.DHCP6PdClientEnableDisableReply")
	api.RegisterMessage((*IP6AddDelAddressUsingPrefix)(nil), "dhcp6_pd_client_cp.IP6AddDelAddressUsingPrefix")
	api.RegisterMessage((*IP6AddDelAddressUsingPrefixReply)(nil), "dhcp6_pd_client_cp.IP6AddDelAddressUsingPrefixReply")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*DHCP6PdClientEnableDisable)(nil),
		(*DHCP6PdClientEnableDisableReply)(nil),
		(*IP6AddDelAddressUsingPrefix)(nil),
		(*IP6AddDelAddressUsingPrefixReply)(nil),
	}
}

// RPCService represents RPC service API for dhcp6_pd_client_cp module.
type RPCService interface {
	DHCP6PdClientEnableDisable(ctx context.Context, in *DHCP6PdClientEnableDisable) (*DHCP6PdClientEnableDisableReply, error)
	IP6AddDelAddressUsingPrefix(ctx context.Context, in *IP6AddDelAddressUsingPrefix) (*IP6AddDelAddressUsingPrefixReply, error)
}

type serviceClient struct {
	ch api.Channel
}

func NewServiceClient(ch api.Channel) RPCService {
	return &serviceClient{ch}
}

func (c *serviceClient) DHCP6PdClientEnableDisable(ctx context.Context, in *DHCP6PdClientEnableDisable) (*DHCP6PdClientEnableDisableReply, error) {
	out := new(DHCP6PdClientEnableDisableReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) IP6AddDelAddressUsingPrefix(ctx context.Context, in *IP6AddDelAddressUsingPrefix) (*IP6AddDelAddressUsingPrefixReply, error) {
	out := new(IP6AddDelAddressUsingPrefixReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion1 // please upgrade the GoVPP api package

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = bytes.NewBuffer
var _ = context.Background
var _ = io.Copy
var _ = strconv.Itoa
var _ = struc.Pack
