// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// source: /usr/share/vpp/api/plugins/ioam_export.api.json

/*
Package ioam_export is a generated VPP binary API for 'ioam_export' module.

It consists of:
	  2 messages
	  1 service
*/
package ioam_export

import (
	bytes "bytes"
	context "context"
	api "git.fd.io/govpp.git/api"
	struc "github.com/lunixbochs/struc"
	io "io"
	strconv "strconv"
)

const (
	// ModuleName is the name of this module.
	ModuleName = "ioam_export"
	// APIVersion is the API version of this module.
	APIVersion = "1.0.0"
	// VersionCrc is the CRC of this module.
	VersionCrc = 0xdb07b979
)

// IoamExportIP6EnableDisable represents VPP binary API message 'ioam_export_ip6_enable_disable'.
type IoamExportIP6EnableDisable struct {
	IsDisable        uint8
	CollectorAddress []byte `struc:"[4]byte"`
	SrcAddress       []byte `struc:"[4]byte"`
}

func (*IoamExportIP6EnableDisable) GetMessageName() string {
	return "ioam_export_ip6_enable_disable"
}
func (*IoamExportIP6EnableDisable) GetCrcString() string {
	return "148b82a4"
}
func (*IoamExportIP6EnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

// IoamExportIP6EnableDisableReply represents VPP binary API message 'ioam_export_ip6_enable_disable_reply'.
type IoamExportIP6EnableDisableReply struct {
	Retval int32
}

func (*IoamExportIP6EnableDisableReply) GetMessageName() string {
	return "ioam_export_ip6_enable_disable_reply"
}
func (*IoamExportIP6EnableDisableReply) GetCrcString() string {
	return "e8d4e804"
}
func (*IoamExportIP6EnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func init() {
	api.RegisterMessage((*IoamExportIP6EnableDisable)(nil), "ioam_export.IoamExportIP6EnableDisable")
	api.RegisterMessage((*IoamExportIP6EnableDisableReply)(nil), "ioam_export.IoamExportIP6EnableDisableReply")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*IoamExportIP6EnableDisable)(nil),
		(*IoamExportIP6EnableDisableReply)(nil),
	}
}

// RPCService represents RPC service API for ioam_export module.
type RPCService interface {
	IoamExportIP6EnableDisable(ctx context.Context, in *IoamExportIP6EnableDisable) (*IoamExportIP6EnableDisableReply, error)
}

type serviceClient struct {
	ch api.Channel
}

func NewServiceClient(ch api.Channel) RPCService {
	return &serviceClient{ch}
}

func (c *serviceClient) IoamExportIP6EnableDisable(ctx context.Context, in *IoamExportIP6EnableDisable) (*IoamExportIP6EnableDisableReply, error) {
	out := new(IoamExportIP6EnableDisableReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion1 // please upgrade the GoVPP api package

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = bytes.NewBuffer
var _ = context.Background
var _ = io.Copy
var _ = strconv.Itoa
var _ = struc.Pack
