// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// source: /usr/share/vpp/api/plugins/cdp.api.json

/*
Package cdp is a generated VPP binary API for 'cdp' module.

It consists of:
	  2 messages
	  1 service
*/
package cdp

import (
	bytes "bytes"
	context "context"
	api "git.fd.io/govpp.git/api"
	struc "github.com/lunixbochs/struc"
	io "io"
	strconv "strconv"
)

const (
	// ModuleName is the name of this module.
	ModuleName = "cdp"
	// APIVersion is the API version of this module.
	APIVersion = "1.0.0"
	// VersionCrc is the CRC of this module.
	VersionCrc = 0x8f707b96
)

// CdpEnableDisable represents VPP binary API message 'cdp_enable_disable'.
type CdpEnableDisable struct {
	EnableDisable uint8
}

func (*CdpEnableDisable) GetMessageName() string {
	return "cdp_enable_disable"
}
func (*CdpEnableDisable) GetCrcString() string {
	return "4eec6097"
}
func (*CdpEnableDisable) GetMessageType() api.MessageType {
	return api.RequestMessage
}

// CdpEnableDisableReply represents VPP binary API message 'cdp_enable_disable_reply'.
type CdpEnableDisableReply struct {
	Retval int32
}

func (*CdpEnableDisableReply) GetMessageName() string {
	return "cdp_enable_disable_reply"
}
func (*CdpEnableDisableReply) GetCrcString() string {
	return "e8d4e804"
}
func (*CdpEnableDisableReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func init() {
	api.RegisterMessage((*CdpEnableDisable)(nil), "cdp.CdpEnableDisable")
	api.RegisterMessage((*CdpEnableDisableReply)(nil), "cdp.CdpEnableDisableReply")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*CdpEnableDisable)(nil),
		(*CdpEnableDisableReply)(nil),
	}
}

// RPCService represents RPC service API for cdp module.
type RPCService interface {
	CdpEnableDisable(ctx context.Context, in *CdpEnableDisable) (*CdpEnableDisableReply, error)
}

type serviceClient struct {
	ch api.Channel
}

func NewServiceClient(ch api.Channel) RPCService {
	return &serviceClient{ch}
}

func (c *serviceClient) CdpEnableDisable(ctx context.Context, in *CdpEnableDisable) (*CdpEnableDisableReply, error) {
	out := new(CdpEnableDisableReply)
	err := c.ch.SendRequest(in).ReceiveReply(out)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion1 // please upgrade the GoVPP api package

// Reference imports to suppress errors if they are not otherwise used.
var _ = api.RegisterMessage
var _ = bytes.NewBuffer
var _ = context.Background
var _ = io.Copy
var _ = strconv.Itoa
var _ = struc.Pack
